version: '3.8'

services:
  backend:
    build: ./backend
    container_name: campushub_backend
    volumes:
      - ./backend:/app
    command: sanic src.server:app --host=0.0.0.0 --port=8000 --debug --auto-reload
    ports:
      - "8000:8000"
    # BURASI DEĞİŞTİ: Artık şifreler burada açıkça yazmıyor
    environment:
      - DB_URL=${DB_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - cache
    networks:
      - hub_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: campushub_db
    # BURASI DEĞİŞTİ: Şifreleri .env'den çekecek
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hub_network
    command: --default-authentication-plugin=mysql_native_password

  cache:
    image: redis:7-alpine
    container_name: campushub_redis
    ports:
      - "6379:6379"
    networks:
      - hub_network

volumes:
  db_data:

networks:
  hub_network:
    driver: bridge